pipeline:
  name: Build go-pipeline-sample-harness
  identifier: Build_Zayan_ahmed953_go_pipeline_sample_harness_1761462668557
  projectIdentifier: ProjectX
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: Zayan-ahmed953/go-pipeline-sample-harness
        build: <+input>
